### ISSUE TITLE
[feature] Image loading

### ISSUE THREAD

**Issue by samdutton** [GoogleChromeLabs/sample-pie-shop#5]
Implement and document image loading strategies.

**Comment by devnook** [comment]
Partially addressed in https://github.com/GoogleChromeLabs/sample-pie-shop/pull/50/commits/0e6a0e0051b860564ef0ad3d56e85eef04cba53f . (Lazy loading with intersectionObserver)

**Comment by samdutton** [comment]
@devnook I'm wondering if the lazy-img element actually makes this more complex than necessary.

What about just adding a `lazy` class and `data-src` attribute to lazy-loaded `img` elements?
