### ISSUE TITLE
[infra] Templates and routes

### ISSUE THREAD

**Issue by rowan-m** [GoogleChromeLabs/sample-pie-shop#7]

**Comment by rowan-m** [comment]
Done:
- Routes
- Templates

Next:
- Webpack config

**Comment by rowan-m** [comment]
AI: Specify the routes - i.e. handled paths, request types, variables.
Need to reach a decision point as soon as possible on writing our own or using a library.

**Comment by rowan-m** [comment]
@sgomes Is it correct to say we now have basic routes and templates? If so, I'd close this in favour of opening new tickets for specific functionality, e.g. additional Webpack configuration, new routing parameter options, etc.

**Comment by sgomes** [comment]
Yes, I think that's probably best. Closing.
